"use strict";
exports.__esModule = true;
exports.UserAction = void 0;
var UserAction;
(function (UserAction) {
    UserAction["CreateRegistrationRequest"] = "CreateRegistrationRequest";
    UserAction["RegisterWithFacebook"] = "RegisterWithFacebook";
    UserAction["FinalizeAccountFromSocial"] = "FinalizeAccountFromSocial";
    UserAction["CreateAccount"] = "CreateAccount";
    UserAction["ResendActivationEmail"] = "ResendActivationEmail";
    UserAction["ConfirmEmailAddress"] = "ConfirmEmailAddress";
    UserAction["SetLogo"] = "SetLogo";
    UserAction["PayOrderViaOnlineCard"] = "PayOrderViaOnlineCard";
    UserAction["Login"] = "Login";
    UserAction["LoginWithFacebook"] = "LoginWithFacebook";
    UserAction["GetRegistrationRequest"] = "GetRegistrationRequest";
    UserAction["ClickOnResetLink"] = "ClickOnResetLink";
    UserAction["SendPasswordResetEmail"] = "SendPasswordResetEmail";
    UserAction["CompletePasswordReset"] = "CompletePasswordReset";
    UserAction["SetBusinessMedium"] = "SetBusinessMedium";
    UserAction["SetProductSuggestion"] = "SetProductSuggestion";
    UserAction["CreateCategory"] = "CreateCategory";
    UserAction["CreateProduct"] = "CreateProduct";
    UserAction["EditCategory"] = "EditCategory";
    UserAction["EditProduct"] = "EditProduct";
    UserAction["ToggleProductStock"] = "ToggleProductStock";
    UserAction["CancelOrder"] = "CancelOrder";
    UserAction["GetCurrentUser"] = "GetCurrentUser";
    UserAction["AdminConfirmBankPayment"] = "AdminConfirmBankPayment";
    UserAction["AdminConfirmDelivery"] = "AdminConfirmDelivery";
    UserAction["AdminRemindExpiry"] = "AdminRemindExpiry";
    UserAction["ViewArticle"] = "ViewArticle";
    UserAction["RequestNewLanguages"] = "RequestNewLanguages";
    UserAction["RequestSetLanguages"] = "RequestSetLanguages";
    UserAction["SucceedSetLanguages"] = "SucceedSetLanguages";
})(UserAction = exports.UserAction || (exports.UserAction = {}));
